// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplySave(arg1:main.SaveData):Promise<void>;

export function GetSavePath():Promise<string>;

export function LoadSave():Promise<main.SaveData>;
