// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySave(arg1) {
  return window['go']['main']['App']['ApplySave'](arg1);
}

export function GetSavePath() {
  return window['go']['main']['App']['GetSavePath']();
}

export function LoadSave() {
  return window['go']['main']['App']['LoadSave']();
}
